### ISSUE TITLE
Unknown field KubeletScraping

### ISSUE THREAD

**Issue by bespokeeagle** [GoogleCloudPlatform/prometheus-engine#228]
Hi guys 
i have the prometheus engine deployed and i'm trying to get metrics from kubelet and Cadvisor by adding the collectionspec.
However i get the error `unknown field "KubeletScraping" in com.googleapis.monitoring.v1alpha1.OperatorConfig.collection`

below is a screenshot of my yaml file

<img width="708" alt="image" src="https://user-images.githubusercontent.com/49434547/168611076-650593b7-4139-4c3f-b0be-465dd9d579db.png">
 please any ideas why this is not working ?

**Comment by lyanco** [comment]
Can you confirm what version of managed collection you are running?

Or if using gcloud to deploy, what GKE version your cluster is running?

**Comment by bespokeeagle** [comment]
> Can you confirm what version of managed collection you are running?
> 
> Or if using gcloud to deploy, what GKE version your cluster is running?

Managed collection beta
GKE version  1.21.10-gke.2000

**Comment by lyanco** [comment]
Got it - so it looks like the version of GMP that haas kubelet scraping (0.4.0) hasn't rolled out to all GKE cluster versions yet, especially slightly older versions. To resolve this, you can do two things:

1. Bump your cluster version; even a slight cluster version bump should do (e.g. 1.21.xx)
2. Wait a little bit of time... within a few weeks older versions will be updated. I don't know when exactly, though.

We're working on making upgrades roll out to all cluster versions at once, so hopefully this issue is temporary.

**Comment by bespokeeagle** [comment]
Hmm Alright much appreciated


> Got it - so it looks like the version of GMP that haas kubelet scraping (0.4.0) hasn't rolled out to all GKE cluster versions yet, especially slightly older versions. To resolve this, you can do two things:
> 
> 1. Bump your cluster version; even a slight cluster version bump should do (e.g. 1.21.xx)
> 2. Wait a little bit of time... within a few weeks older versions will be updated. I don't know when exactly, though.
> 
> We're working on making upgrades roll out to all cluster versions at once, so hopefully this issue is temporary.

Hmm alright much appreciated

**Comment by bespokeeagle** [comment]
> Can you try again?

just did,

works fine now 

Thanks @lyanco
