### ISSUE TITLE
Monitoring services without selectors

### ISSUE THREAD

**Issue by NibiruHeisenberg** [GoogleCloudPlatform/prometheus-engine#362]
Hi,

Our team uses Services without selectors to access external services outside our k8s cluster (running in VMs in GCE), which exposes a Prometheus formatted /metrics endpoint. How can I scrape these endpoints using Google Managed Prometheus? PodMonitoring won't work here since no actual pods are running in k8s representing these external services. Prometheus Operator has a ServiceMonitor CRD, which could be used here, but there doesn't seem to be an equivalent in GMP.

Thanks in advance.

**Comment by pintohutch** [comment]
Hi @NibiruHeisenberg,

This issue was raised and is being tracked in #192. There's a suggested [workaround](https://github.com/GoogleCloudPlatform/prometheus-engine/issues/192#issuecomment-1112722175) in that issue. Happy to discuss more there if you have some concrete details.

I'm going to close this as a duplicate for now.

**Comment by lyanco** [comment]
You can also do this with Self-deployed collection: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-unmanaged

**Comment by lyanco** [comment]
I don't think that's the case. You can deploy a self-deployed collector using prometheus-operator and then use that library's ServiceMonitor CRs to serve your use case.
