### ISSUE TITLE
Unaccessible routes from the Prometheus server

### ISSUE THREAD

**Issue by arthurburle** [GoogleCloudPlatform/prometheus-engine#513]
Hi everyone,

I'm running a Kubernetes cluster (master and workers at `1.24.12-gke.500`). I have a prometheus frontend and I am able to fetch metrics from the Prometheus API perfectly with my Grafana instance.

The problem is that my Grafana is not able to fetch rules from the managed Prometheus because routes such as: `/api/v1/rules` or `/api/v1/status/buildinfo` aren't [supported](https://cloud.google.com/stackdriver/docs/managed-prometheus/query#http-api-details).
<br>
**Question 1**: Am I looking at the right endpoint? Is this the same Prometheus instance that is responsible for sending alerts to the alertmanager?

**Question 2**: In case this is the right endpoint and these routes are just not yet compatible, is there a plan in the roadmap for enabling them?

![image](https://github.com/GoogleCloudPlatform/prometheus-engine/assets/71952635/876eed3c-6657-40ab-9b08-0fee420edf91)

**Comment by lyanco** [comment]
/rules and /alerts are not supported because there isn't any central Prometheus server that's executing rules or alerts - Rules are configured locally across multiple clusters, executed by running queries against the API, and then the results get routed to a local alertmanager. You set up Grafana to globally query the Cloud Monitoring APIs, and the APIs don't know anything about the rules and alerts configured locally, so we can't easily support these endpoints right now.

We will soon be launching fully managed PromQL alerts in Cloud Alerting, which will feature centrally-configured rules and alerts. Once that's out you'll be able to view your configured rules and alerts in one place, and it will be possible for us to implement these endpoints and have it make sense.

**Comment by arthurburle** [comment]
Thanks a lot for the quick answer. Could you give me any idea of when this could happen?

**Comment by lyanco** [comment]
We're likely to enter public preview without a UI this or next month; in GA and with a UI towards the end of the year or beginning of next year.
