### ISSUE TITLE
example metrics with 2.3.0 will no longer suitable for gke 1.25 and later

### ISSUE THREAD

**Issue by leitu** [GoogleCloudPlatform/prometheus-engine#547]
As GKE dashboard shows, we need to migrate to validate version after gke upgrade to 1.25, as I checked with our own app, all APIs seems fine, but we can see all the api invalidate calls from kube-state-metrics with 2.3.0. we need to separate the version for before 1.25, or we just update the docs directly

**Comment by leitu** [comment]
<img width="791" alt="errors" src="https://github.com/GoogleCloudPlatform/prometheus-engine/assets/2867202/ee6171e0-8bd2-4195-bfd0-9a65c1d59c79">
dashboard warnings
<img width="1421" alt="logs" src="https://github.com/GoogleCloudPlatform/prometheus-engine/assets/2867202/e11ee79e-4b71-4200-b6f0-ca3d73912208">
logs in detail

**Comment by yqlu** [comment]
I see, yes we should bump
https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/examples/kube-state-metrics/kube-state-metrics.yaml#L20 (or recommend two different versions based on GKE version)
which is being hosted in 
https://cloud.google.com/stackdriver/docs/managed-prometheus/exporters/kube_state_metrics

@TheSpiritXIII happy to take over this request because GMP is WAI -- we'll just need to refresh our copy-pastable exporter configs
