### ISSUE TITLE
RemoteRead or Thanos sidecar support

### ISSUE THREAD

**Issue by arthurh4** [GoogleCloudPlatform/prometheus-engine#735]
Hello, our company is running a distributed prometheus setup across cloud providers and data centers using Thanos.

We would like to support GCP managed prometheus setup in our Thanos setup.

I've tried several things:
- Deploy the forked GCP prometheus: Seems like it's only used for ingesting data into GCP managed prometheus not querying or could not find any info.
- Deploy the thanos sidecar with GCP prom frontend and getting error from sidercar for external labels fetch:
```
/v1/projects/PROJECT_ID/location/global/prometheus/api/v1/status/config</code> was not found on this server.
```
- Try remote read from a native prometheus to GCP prom frontend but getting:
```
GET /graph HTTP/1.1
Host: frontend.devops-gcp-monitoring.svc.cluster.local:9090
User-Agent: Prometheus/2.41.0
Accept-Encoding: snappy
Content-Encoding: snappy
Content-Type: application/x-protobuf
Referer: http://frontend.devops-gcp-monitoring.svc.cluster.local:9090
X-Prometheus-Remote-Read-Version: 0.1.0

HTTP/1.1 200 OK
Date: Fri, 22 Dec 2023 19:00:32 GMT
Content-Length: 752
Content-Type: text/html; charset=utf-8

<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="shortcut icon" href="./favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no"/><meta name="theme-color" content="#000000"/><script>const GLOBAL_CONSOLES_LINK="",GLOBAL_AGENT_MODE="AGENT_MODE_PLACEHOLDER",GLOBAL_READY="READY_PLACEHOLDER"</script><link rel="manifest" href="./manifest.json" crossorigin="use-credentials"/><title>Google Cloud Managed Service for Prometheus</title><script defer="defer" src="./static/js/main.af1f148a.js"></script><link href="./static/css/main.4858e794.css" rel="stylesheet"></head><body class="bootstrap"><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>POST / HTTP/1.1
Host: frontend.devops-gcp-monitoring.svc.cluster.local:9090
User-Agent: Prometheus/2.41.0
Content-Length: 201
Accept-Encoding: snappy
Content-Encoding: snappy
Content-Type: application/x-protobuf
X-Prometheus-Remote-Read-Version: 0.1.0

HTTP/1.1 302 Found
Location: /graph
Date: Fri, 22 Dec 2023 19:00:45 GMT
Content-Length: 0
```

Is there any options to achieve this ? Otherwise are they any plans to support this pattern ?
Ideally having the frontend proxy work with a thanos sidecar would be ideal/fantastic with a specific external label, Thank you.

**Comment by bwplotka** [comment]
Hi! Great question. We don't currently support this (not officially), but there might be some workarounds here, plus future experiments. Let's unpack it:

Sounds like you want to connect your GCP monitoring to Thanos (specifically your GKE clusters with managed collection, right?). Are you interested specifically in "read" mode? (remote-read/sidecar/Thanos StoreAPI) or remote write would solve your problem too?

From a high level point of view your attempts were solid. In theory, we could try getting metrics from your GKE clusters to Thanos in two ways:

1. Use local cluster metric collection -> Thanos
2. Use local cluster metric collection (e.g. recommended [GMP Managed Collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed)) -> Google Cloud [GMP service](https://cloud.google.com/stackdriver/docs/managed-prometheus) (part of Google Cloud Monitoring) -> Thanos

### 1. Cluster -> Thanos

In this case we could try getting metrics directly from the cluster metric collection either via remote-write or read (with sidecar) to Thanos. In the simplest scenario you can skip GMP totally and use classic methods like manual Prometheus setup, Prometheus Operator or anything else that supports Thanos sidecars or remote-writing to Thanos.

I assume you added this issue, because for some reason you would like to use:
a. collection that is managed, default on GKE or...
b. GMP operator with scalable daemonSet pattern or..
c.  perhaps you want ingest metrics to both GMP/GCM service AND Thanos

.. or mix of those (: (which one?) 

For (a), indeed we don't support this case with [GMP managed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed) and currently we don't plan to add it.

For (c), you can totally deploy our [forked GMP Prometheus](https://github.com/GoogleCloudPlatform/prometheus) (our fork simply adds GCM API support, nothing else) without operator or with Prometheus Operator and configure it to export to GMP, as well as add sidecar/remote-write. All of this should be possible with Prometheus Operator flexible configuration (extra arguments). We also work hard to support native remote write in GCM, which will get rid of fork.

For (b), unfortunately you can't configure remote-write yet (this requires operator code changes). We plan to add that sooner or later. However, you should be able to use self-deployed GMP operator with Thanos sidecar, if it makes sense for you. We might make it more easy in the future (ideas or even contributions are welcome!), but you should be able to do it now e.g. (theory, not tested):

1. Disable [managed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#disable-mgdcoll-gke) on your cluster
2. Go to this repo `manifests/operator.yaml` and adapt [Prometheus DaemonSet ](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/main/manifests/operator.yaml#L606) to your needs. E.g. add Thanos sidecar, expose port, add necessary HTTP service that will route to each sidecar (not load balance!) change limits etc.
3. Apply `manifests/setup.yaml` then `manifests/operator.yaml` YAMLs.
4. Done, you can use [PodMonitoring](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed#gmp-pod-monitoring) etc.

Question is, is (b) + sidecar really a good idea. Thanos will have to discover and query each Prometheus pod per node for potentially every PromQL query if you don't setup and use external labels correctly. For multiple clusters with hundreds nodes (e.g. 10k StoreAPIs), without proper label matcher enforcing this might be tricky.

Remote-write with (b) might be better, let us know if you would like us to add it for the self-deployed operator scenario.

### 2. GMP/GCM -> Thanos

 This is even more interesting, because there are various (free) system metrics that go through different mechanisms than [GMP managed collection](https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed). You might also add metrics from other GCP systems using managed flows (Cloud Run, GCE etc). This is not currently possible without some additional custom code on top.

frontend proxy (as you noticed) is not helpful for this case at the moment. External labels are not a huge problem, we could find a way (e.g. allow configuring them), but GCM/GMP cloud service does not support [remote-read](https://prometheus.io/docs/prometheus/latest/querying/remote_read_api/) API. 

Potential solutions in future or for brave programmer: 

a. One could implement remote-read (or even directly StoreAPI) against GCM API e.g. using [ListTimeSeries](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list) gRPC/HTTP API inside frontend or other proxy. Perhaps possible with some limitations (e.g. ListTimeSeries allows retrieving only one metric type per call).
b. One could utilize a new (a bit hidden for now) [QueryAPI](https://github.com/thanos-io/thanos/blob/cf94c2f151e7c4cda14f264066174ddd697b37cd/pkg/api/query/v1.go#L140) in Thanos. I don't want to spoil too much, but we might have something to show about this in the upcoming [ThanosCon in Paris in March](https://www.cncf.io/blog/2023/11/28/introducing-thanoscon-in-paris-kubecon-cloudnativecon-eu-2024/). With some extra code and Thanos setup this allows similar flow.

cc @macxamin @fpetkovski @pintohutch @lyanco

**Comment by r0bj** [comment]
We use multiple Prometheus servers and employ Thanos as a single endpoint to query metric data from these Prometheus servers. Additionally, we use the GMP frontend to query metrics native to the GCP cloud, such as GCP load balancer metrics. Implementing a Thanos sidecar with the GMP frontend would be highly beneficial. This setup would enable Thanos to query metrics both from our local Prometheus servers and from the Google Cloud Managed Service for Prometheus (GMP).

**Comment by bwplotka** [comment]
👋🏽 

I believe this use case is now solved thanks to @maxamins and @fpetkovski work, but without using classing Thanos sidecar or remote read.

**Essentially it is now possible to query GMP/GCM from Thanos Querier and join data from other Thanos (or any other) sources**

How:
* Add extra Thanos Querier on top of your Thanos cluster (or any other PromQL enabled endpoint) with `--query.mode=distributed` flag. It will pushdown PromQL queries to all your endpoints and aggregate on the top level.
* Deploy light proxy (https://github.com/thanos-community/thanos-promql-connector) next to that top level Thanos Querier that can translate any HTTP PromQL endpoint to Thanos gRPC Query API, allowing (for example) to connect GMP/GCM HTTP PromQL endpoint to Thanos system.

This was explained in the KubeCon EU ThanosCon talk ([slides](https://docs.google.com/presentation/d/1H9DjwE0C6yZmD759GgBBuFVhgA72Az1GiAYvKRMCDHs/edit), recording available soon). We are discussing adding proper documentation and blog posts about this too. 

Feedback welcome @r0bj @arthurh4 etc, but in the meantime I will close this issue as fixed 🤗

**Comment by r0bj** [comment]
Thank you @bwplotka.
It seems that recording "Connecting Thanos to the Outer Rim via Query API " you mentioned is already available: https://www.youtube.com/watch?v=E8L8fuRj66o
