### ISSUE TITLE
Create a helm chart for the frontend service

### ISSUE THREAD

**Issue by AndresPinerosZen** [GoogleCloudPlatform/prometheus-engine#935]
User experience could be improved with a Helm chart. I want to query Managed Prometheus using the auth proxy (frontend) but before that I need to create a Helm chart for these resources.

I could share the one I'll create in a PR but I'm not sure it will match your standards.

**Comment by bernot-dev** [comment]
We recently started using a Helm chart internally to generate manifests in #817. However, the maintainers have some reservations about supporting Helm directly for users as an install path.

Among these concerns:

1. Handling CRDs with Helm can be messy. Basically, Helm does not update CRDs after a chart is installed, which could lead to undesirable behavior. You can also maintain a separate chart, but this increases the maintenance burden.
2. Google Cloud uses tools other than Helm internally to customize manifests for GKE, for instance. When GMP is installed as a GKE component, Helm would not add value. Maintaining multiple install methods is unlikely to be a priority for us without substantial interest from users.
3. There is a lot of potential for feature sprawl with Helm. Some users who deploy GMP on their own do so because they can customize the components to their preferences. To support Helm effectively, We would need to ensure that these customizations are supported. However, the maintenance burden to continue implementing these options would probably have fairly minimal broad value to the wider user base.

We do accept contributions. However, we may also have considerations like value added and maintainability that weigh heavily on whether a contribution like this would be accepted.

You may also be interested in using our internal chart as a starting point, and then creating your own chart to meet your needs exactly.

**Comment by bernot-dev** [comment]
Closing this issue for now. Feel free to follow up with additional questions/concerns.
