### ISSUE TITLE
Support of Job and CronJob monitoring

### ISSUE THREAD

**Issue by AndrasSandor** [GoogleCloudPlatform/prometheus-engine#987]
Currently kube job metrics, such as kube_job_status_failed or kube_job_status_succeeded are not made available for monitoring.
List of metrics:
https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/job-metrics.md

**Comment by maxamins** [comment]
@AndrasSandor let us know if @lyanco suggestion works for you. Closing this issue for now. 

Future readers feel free to +1 or reopen this thread if there is demand for this feature.

**Comment by ksoftirqd** [comment]
It would be great to add `jobs`/`cronjobs` related metrics to the list. The volume would likely be insignificant. However, I assume, it would need to be explicitly enabled to impact costs.

The alternative options are not appealing:

- Deploying self-managed kube-state-metrics instead of the managed one does not offer the ability to “honor” reserved labels, like `namespace`/`pod` etc, leading to a confusing set of labels (e.g. `namespace`/`exported_namespace`, etc) and the need to modify existing rules.
- Deploying pushgateway and modifying all jobs to push metrics to pushgateway would add complexity and require additional effort

**Comment by pintohutch** [comment]
Hey @ksoftirqd - thanks for reaching out.

> Deploying self-managed kube-state-metrics instead of the managed one does not offer the ability to “honor” reserved labels, like namespace/pod etc, leading to a confusing set of labels (e.g. namespace/exported_namespace, etc) and the need to modify existing rules.

Actually by specifying a ClusterPodMonitoring like we show in [`examples/`](https://github.com/GoogleCloudPlatform/prometheus-engine/blob/79545c99c337a0907be9921c674840513cae8a8a/examples/kube-state-metrics/kube-state-metrics.yaml#L305-L327), you should have those labels honored by the kube-state-metrics exporter. Have you tried this?

**Comment by ksoftirqd** [comment]
Hi @pintohutch,

Thank you, this is very helpful! I must have missed this example and it indeed works as expected.

If we cannot add jobs/cronjobs to the list of supported resources, this can be a great alternative to the managed kube-state-metrics exporter.

Still it would be great to see those resources added, as the current solution seems to support the majority of resources and it's possible to toggle their metrics collection in the cluster config.
